---
title: "gapminder explorer"
output:
  pdf_document: default
  html_document: default
date: "2025-03-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
```

## Exploring Gapminder

Load data

```{r}
gapminder <- read.csv("../data/gapminder_data.csv")

```


how can I compare life expectency by country?

here's function that makes a **panel plot** using `facet_wrap` on country

make sure to filter on continent otherwise it's unreadable

```{r}
# using facet_wrap on country
gapminder_by_continent <- function(df, Continent){
  gm_plot <-  df %>% filter(continent == Continent) %>%
  ggplot(mapping = aes(
  x=year, y = lifeExp, color = continent)) +
  geom_line() + 
  facet_wrap( ~ country) + 
  theme(axis.text.x = element_text(angle = 45, size=8)) +
  labs(title = "Life Expectancy by Year", 
       x = "Year", 
       y = "Life Expectancy", 
       color = "Continent")
  
  return(gm_plot)
}

```

loop through all continents: 

```{r}
for(continent in unique(gapminder$continent)) {
  gm_plot <- gapminder_by_continent(gapminder, continent)
  print(gm_plot)
}
```
